### PR TITLE
[33] Renamed example package to irods

### PR DESCRIPTION
**Pull request by sam-i-am012**
Addresses #33 
Not sure if this is a good name for the package?

### CODE REVIEW

**Comment by korydraughn** [comment]
Use `org.irods` for the package name.

**Comment by sam-i-am012** [comment]
Done.

**Review by korydraughn — APPROVED** [review]
Looks good. If the tests pass, pound it.

**Comment by sam-i-am012** [comment]
Done.

**Comment by korydraughn** [comment]
Merging.

**Pull request merged**
