### PR TITLE
Implement tests for Collections endpoint

### PR DESCRIPTION
**Pull request by sam-i-am012**
Continuing #45 after accidental closure.

### CODE REVIEW

**Comment by korydraughn** [comment]
Please address the review comments from the previous PR.

**Comment by sam-i-am012** [comment]
All the review comments from the previous PR have been resolved.

**Comment by korydraughn** [comment]
Do the tests pass?

**Comment by sam-i-am012** [comment]
Yep, everything passed.

**Comment by korydraughn** [comment]
Good. Squash to taste. No pounds.

**Comment by sam-i-am012** [comment]
Done.

**Review by korydraughn — APPROVED** [review]
Looks ready.

Pound it.

**Comment by sam-i-am012** [comment]
Done.

**Comment by korydraughn** [comment]
You're getting good at this. Keep it up!

Merging.

**Pull request merged**
