### PR TITLE
[53] Swap operands to (null != params)

### PR DESCRIPTION
**Pull request by sam-i-am012**
Addresses #53

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Looks good.

Do the tests still pass?

**Comment by sam-i-am012** [comment]
Yes, tests are all still passing.

**Review by korydraughn — APPROVED** [review]
Pound it.

**Comment by sam-i-am012** [comment]
Done.

**Comment by korydraughn** [comment]
Merging.

**Pull request merged**
