### PR TITLE
Addressed some smaller issues. 

### PR DESCRIPTION
**Pull request by sam-i-am012**
Deleted unused classes and fixed something in `testAddingRemovingAndModifyingZones` in `zoneOperationsTest`

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
The commit targeting issue 93 handles two things. The addition of the `throws JsonProcessingException` should be linked to a different issue.

Please split the commit into two or change the commit message to start with `[91,93]`.

**Comment by sam-i-am012** [comment]
Ugh, I forgot I did that. Changing it now.

**Comment by sam-i-am012** [comment]
It's been changed.

**Review by korydraughn — APPROVED** [review]
Pound it if the tests are passing.

**Comment by sam-i-am012** [comment]
Done.

**Comment by korydraughn** [comment]
Merging.

**Pull request merged**
